### ISSUE TITLE
define a managment tool for CLAW project

### ISSUE THREAD

**Issue by lxavier** [C2SM-RCM/claw-language-definition#1]
DOD: appropriate tool in use

**Comment by lxavier** [comment]
DOD: appropriate tool in use

**Comment by cosunae** [comment]
asana is free up to 15 users

**Comment by lxavier** [comment]
@cosunae  Did you try it ? An other solution would simply be to use the github issues system. It would be possible to have an agile like workflow using the Milestones

**Comment by cosunae** [comment]
I didnt use it, but I heard from paolo is a good tool. 
github is very minimalistic, for keeping track of the tasks is good enough, and we can have milestones but you can not manage time

**Comment by clementval** [comment]
The tool I was telling you https://trello.com. Basic features are free. You define a board for the project and then list that contains task that you can move between them.
