### ISSUE TITLE
Deal with elemental function

### ISSUE THREAD

**Issue by clementval** [C2SM-RCM/claw-language-definition#15]
In fortran, we can declare `ELEMENTAL` subroutines and functions. These subroutines/functions take scalars as arguments but can be called with arrays as well. 

Using `!$claw parallelize` in an `ELEMENTAL` subroutine or function will transform it or not depending of the target architecture. For `GPU`, it will transform to function to accept arrays of the correct dimension and remove the `ELEMENTAL` keyword. On the calling site, the `!$claw parallelize forward` directive allows the call to the `ELEMENTAL` function to be adapted as well. 

### Example using elemental function with vector notation
Here is an example of an `ELEMENTAL` function. 
```fortran
module mo_elemental
  real, parameter :: coef1 = 5.12345678
  real, parameter :: coef2 = 2.98765424
contains
 real elemental function do_some_stuff(arg1, arg2)
  real, intent(in) :: arg1, arg2
  do_some_stuff = arg1 * coef1 * ( 1.0 + coef2 * arg2)
 end function do_some_stuff
end module mo_elemental
```

and how to call it with arrays
```fortran
program elemental_test
  use mo_elemental
  real, dimension(100) :: arg1, arg2, res
  integer :: i
  do i = 1, 100
    arg1(i) = i*i
    arg2(i) = i+i
  end do
  res(:) = do_some_stuff(arg1(:), arg2(:))
  print*, sum(res(:))
end program elemental_test
```

The idea is to specify how to deal with these constructs with `CLAW` directives

### Version annotated with current CLAW SCA directive (see #12 for possible change)
```fortran
module mo_elemental
  real, parameter :: coef1 = 5.12345678
  real, parameter :: coef2 = 2.98765424
contains
 real elemental function do_some_stuff(arg1, arg2)
  real, intent(in) :: arg1, arg2

  !$claw define dimension horizontal(1:nc) &
  !$claw parallelize
  do_some_stuff = arg1 * coef1 * ( 1.0 + coef2 * arg2)
 end function do_some_stuff
end module mo_elemental
```
```fortran
program elemental_test
  use mo_elemental
  real, dimension(100) :: arg1, arg2, res
  integer :: i
  do i = 1, 100
    arg1(i) = i*i
    arg2(i) = i+i
  end do

  !$claw parallelize forward
  res(:) = do_some_stuff(arg1(:), arg2(:))
  print*, sum(res(:))
end program elemental_test
```

### Automatic transformed version from the CLAW Compiler
```fortran
module mo_elemental
  real, parameter :: coef1 = 5.12345678
  real, parameter :: coef2 = 2.98765424
contains
function do_some_stuff(arg1, arg2,nc)
  integer, intent(in) :: nc
  real, dimension(1:nc), intent(in) :: arg1, arg2
  real, dimension(1:nc) :: do_some_stuff
  integer :: horiz_iter

  !$acc parallel
  !$acc loop gang vector
  do horiz_iter = 1, nc
    do_some_stuff(horiz_iter) = arg1(horiz_iter) * coef1 * ( 1.0 + coef2 * arg2(horiz_iter))
  end do
  !$end parallel
 end function do_some_stuff
end module mo_elemental
```

```fortran
program elemental_test
  use mo_elemental
  real, dimension(100) :: arg1, arg2, res
  integer :: i

  do i = 1, 100
    arg1(i) = i*i
    arg2(i) = i+i
  end do

  !$acc data create(arg1, arg2,res)  
  !$acc update device(arg1, arg2)
  res = do_some_stuff(arg1, arg2, nc)
  !$acc update host(res)
  !$acc end data
  print*, sum(res(:))
end program elemental_test
```

**Comment by phmarti** [comment]
Doesn't your claw example fix the dimension and dimensionality?

What happens if there are two calls to `do_some_stuff` with different size/dimensionality?

**Comment by clementval** [comment]
@phmarti Well the example was missing someting. I updated the transformed code as it would be normally. So the size can be changed at runtime but the dimensionality would be fixed in this case. Have to see if we have to support different dimensionality ...

**Comment by lxavier** [comment]
looks perfect to me. there are no data (present) statement in the generated elemental function do_some_stuff but I assume it is just a typo

**Comment by clementval** [comment]
PR #24
